version: "3.8"
services:
  web:
    build: ./app
    image: 981960797902.dkr.ecr.us-east-1.amazonaws.com/final_prj:final_prj_web
    command: gunicorn dvd_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=dvdrental_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=dvdrental.corjevpvhgko.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-44-212-136-160.compute-1.amazonaws.com
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: 981960797902.dkr.ecr.us-east-1.amazonaws.com/final_prj:final_prj_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume: